### ISSUE TITLE
Push new version to pypi

### ISSUE THREAD

**Issue by rob-b** [rob-b/pytest-blockage#7]

**Comment by rouge8** [comment]
Looks like 0.3.0 is tagged in the repo. Is there anything holding up a PyPI release?

**Comment by saily** [comment]
after merging #8 I'd love to see a new release on pypi.

**Comment by andrewshkovskii** [comment]
+1

**Comment by vad** [comment]
You're right, I'll do it this week

**Comment by vad** [comment]
@andrewshkovskii @saily @rouge8 0.2.1 is out! (the changelog was already sort of ready for 0.2.1)
